Hubs-Foundation/hubs-ops

- terraform/live/dev/ret/terraform.tfvars
- terraform/modules/base/main.tf
- terraform/modules/base/output.tf
- terraform/modules/ret/main.tf
- terraform/modules/ret/vars.tf
For https://github.com/mozilla/reticulum/issues/4
adds CF endpoint for reticulum assets that is backed by the server as origin
> Add cloudfront distribution for reticulum assets

- ansible/roles/ret/templates/janus-gateway.toml.j2
- plans/janus-gateway/habitat/config/janus.eventhandler.sqlite.cfg
- plans/janus-gateway/habitat/default.toml
- plans/janus-gateway/habitat/plan.sh
They'll go in /hab/svc/janus-gateway/var/events.db.
The only events that get logged right now are events that you would characterize as "connection state updates", e.g. someone attached a plugin handle, someone negotiated a WebRTC connection, someone disconnected their websocket. So the database size should remain small under any reasonable load and we shouldn't have to worry about rotating it or truncating it or anything at the moment.
I bumped the Janus gateway version, because we needed recent changes to the event handler API. There shouldn't be any visible changes though.
> Log Janus events to SQLite DB

- plans/janus-gateway/habitat/plan.sh
Seems like it's better to pin everything and update explicitly since we will sometimes want to update only upstream Janus.
> Pin Janus version in Habitat plan

- plans/janus-gateway/habitat/plan.sh
Remarkably, Habitat strips them by default, which is sad news for our crash diagnosing efforts.
> Retain debug symbols in Janus binary

- packer/hab-base/image.json
This should be an easy upgrade, since all of the "heavy lifting" on these boxes is inside Habitat.
As of the time of this writing, I applied this AMI to all of the dev cluster boxes; that's hab, ci, ret, and janus. I'm waiting to apply it to prod for when Greg is around and when we're willing to accept downtime (since Janus has no redundancy and no way to migrate users from one box to the next.)
> Bump hab base to Ubuntu 18.04

- packer/bastion/image.json
I created and tested a new AMI from this with a new TOTP secret. I'm going to hold off upgrading instances to the new AMI until Monday when I can tell everyone the secret.
> Bump bastion base to Ubuntu 18.04, cycle TOTP secret

- plans/janus-gateway/habitat/plan.sh
Included:
- Less logspam on verbose Janus logging.
- Patch for SRTP profile detection on weird client bug.
- Patch for DTLS BIO negative length bug.
- Remove string ID backwards compat from Janus plugin.
> Bump Janus, plugin versions

- terraform/modules/janus/main.tf
During busy times we hit the previous limit, thereby dropping some log entries, which is bad. Disk space is not an issue.
> Apply more generous rate limit to Janus logs

- ansible/roles/janus/templates/janus-gateway.toml.j2
- terraform/modules/janus/main.tf
This will let people use Hubs even in networks that don't permit UDP, which is cool.
> Support Janus over TCP

- ansible/roles/janus/templates/janus-gateway.toml.j2
- terraform/modules/janus/main.tf
Turn Janus down to INFO while simultaneously increasing the journald log limit back to a reasonable value.
> Adjust logging for Janus

- terraform/modules/ci/main.tf
Necessary in some cases for fetching dependencies for our hubs client.
> Open git protocol port on CI security groups

- ansible/roles/janus/tasks/main.yml
For some reason specifying HAB_BUTTERFLY_BINARY, which apparently was working fine at some point, stopped working. Fortunately for us there seems to be no reason to use it anyway.
> Invoke hab-butterfly directly for file uploads

- helpers.sh
It turns out that /results is created relative to the current directory, not the plan directory.
> Habitat helper script tweak

- plans/janus-gateway/habitat/plan.sh
Also pin dependency versions, since we are too lazy to upgrade them right now. We will upgrade them later when we're not trying to deploy this feature.
> Bump Janus for JWT-based kick support

- workers/cors-proxy.js
Spoke is currently using Farspark for all media when working in development. This PR adds `https://hubs.local:9090` as an allowed origin so that we can use the cors-proxy in development
> Add Spoke origin to cors-proxy whitelist

- db/ret0_admin/sql/V7__avatar_listings_views.sql
This contains the necessary migrations to support the avatar admin interface.
https://github.com/mozilla/reticulum/pull/169 must go out before this PR as it creates the avatar_listings table and updates the avatars table.
> Add migration for avatar listings admin views

- db/ret0_admin/sql/V7__avatar_listings_views.sql
- db/ret0_admin/sql/V8__add_gltf_to_avatar_listings.sql
- helpers.sh
Adds these columns to the admin views. Fixes promoting avatars with a custom glb set (which there will be a lot more of soon since we will be exposing this directly instead of behind a flag).
Also adds a helper for tunneling the dev admin postgrest.
> Fix gltf/bin files not being returned on listings in admin views

- plans/janus-gateway/habitat/plan.sh
This is necessary to get fixes related to mDNS ICE candidates for Chrome. See:
- https://github.com/meetecho/janus-gateway/commit/0a5f379ad3bc521718cd0fb90e3008a09837baff
- https://groups.google.com/d/msg/discuss-webrtc/4Yggl6ZzqZk/yawz3VVLDgAJ
- https://groups.google.com/d/msg/discuss-webrtc/4Yggl6ZzqZk/GaGLSpRTDgAJ
- https://groups.google.com/d/msg/discuss-webrtc/4Yggl6ZzqZk/Hjd84-1UDgAJ
It also contains a few other interesting bugfixes, like https://github.com/meetecho/janus-gateway/pull/1356, although not obviously any ones that are super important to us.
> Bump Janus 0.4.3->0.4.5

- db/ret0_admin/sql/V9__add_parent_avatar_listing_id_to_avatar_listings.sql
parent_avatar_listing_id does not get copied over when approving an avatar in the admin console since the `pending_avatars` view was missing this column
> Add parent_avatar_listing to pending_avatars_view

- helpers.sh
Now it doesn't screw up the formatting when column contents have spaces (e.g. someone has made a host named "QEMU Image Builder") because it knows the difference between spaces and tabs.
> More accurate columnization of moz-ec2 output

- terraform/modules/ci/main.tf
We use this script in Jenkins jobs to deploy client code for Hubs and Spoke
> Add missing hab-user-toml-install script

- cloudformation/stack.yaml
DialogExternal on an app server uses port 8443 (ret is using 443 on app server)
DialogExternal on a streaming server uses port 443
Turn is always on 5349
> Dialog remove 80

- cloudformation/stack.yaml
Added permissions to "app", "app,stream" boxes for running cleanup_records cron job.
IAM Permissions added:
- EC2 describe-instances
- Route53 describe records
- Route53 changeset to delete records
- Auto scaling describe auto scaling groups
> Cleanup A records: add IAM permissions for EC2, Route53, auto scaling to run cron job

- cloudformation/stack.yaml
In https://github.com/mozilla/reticulum/pull/508 we added a restriction that prevents uploads being served from the primary domain. That change worked on HMC, but not on the current Hubs Cloud release candidate, since the CloudFront configuration in our CloudFormation stack is not configured to pass the Host header along to the server. As a result, uploaded files, including scenes and avatars fail to load.
This PR adds the required header to fix this issue.
> Add Host header to Hubs Cloud CloudFront behavior to fix upload requests

- workers/cors-proxy-internal.js
The code for the internal cors proxy here didn't actually match the code that we currently have deployed to production.
I'm not sure why the code differs. It seems the code in the repo had additional functionality to cache files and assets from reticulum and S3, presumably in an attempt to save on bandwidth or load, but we either never deployed this version, or we reverted it at some point. In either case, it's best if the code in the repo matches what we actually have in production.
> Update cors proxy to match the one in production

- terraform/modules/ret/main.tf
Related to https://github.com/mozilla/reticulum/pull/541
We need to forward the user-agent header through the uploads distribution in order to apply CSP headers correctly.
> Forward user-agent header in uploads cloudfront distribution

- cloudformation/stack.yaml
It seems v0.0.1 of speelycaptor, which we deployed during the last set of lambda updates, actually contained old code that broke video uploads. We deployed v0.1.3 to fix this, using the latest code from https://github.com/mozilla/speelycaptor
> Update speelycaptor version to use a version with the latest code

- cloudformation/stack.yaml
This fixes website screenshots that were returning 500s because the node runtime version wasn't updated to the latest on Hubs Cloud.
> Updated photomnemonic version to 0.3.0

- ansible/roles/ret/templates/reticulum.toml.j2
Adds a section and token field for the new whats-new API. 
Goes with https://github.com/mozilla/reticulum/pull/559
> Add whats new token to reticulum ansible template

- .github/workflows/HcPkgPreReleaseGitops.yaml
This will enable automatic branch pointer movement and next-release tagging.
> New post release workflow for hubs cloud packages 
