ansible/roles/janus/templates/janus-gateway.toml.j2
plans/janus-gateway/habitat/config/janus.plugin.sfu.cfg
plans/janus-gateway/habitat/default.toml

Contemporanously, the Janus plugin was updated to support this as well as with a few new features.

Add SFU config with room cap

---

terraform/modules/ret/main.tf

https://www.terraform.io/docs/providers/aws/d/acm_certificate.html leads me to
believe that this is the correct syntax for switching from the "imported"
certs to the "amazon issued" certs.
It is important to switch to the amazon issued certs because renewal goes:
* Request new cert
* Have someone subscribed to hostmaster@mozilla.com click the link to approve
* Use new cert (though I do not yet know how to tell Terraform to take the
newer of multiple amazon issued certs; we can sort that out next year)
As opposed to the old way where moz IT generated the cert and gpg'd it up and
emailed it to me, with me as a SPOF.
Also I stripped a bunch of whitespace from blank lines because wtf whitespace on blank lines i don't even.

Switch from Moz IT certs to ACM-issued certs

---

plans/janus-gateway/habitat/plan.sh

This has some Janus bugfixes, fix to overly verbose Janus core log output, and substantially improved Janus SFU log output.

Bump Janus & SFU versions

---

ansible/roles/squawk/tasks/main.yml
ansible/roles/squawk/templates/squawkers.sh.j2
ansible/roles/squawk/vars/main.yml

The squawker role now uses a bot implementation that is built into the Hubs app. See mozilla/hubs#370

Use hubs-based bots

---

plans/janus-gateway/habitat/plan.sh

This includes ICE- and SCTP-related changes that may impact both the [ICE CPU performance problem](https://github.com/meetecho/janus-gateway/issues/1260) we are monitoring and [a recent SCTP thread crash](https://github.com/meetecho/janus-gateway/issues/1247).

Janus 0.4.2

---

plans/janus-gateway/habitat/plan.sh

Enable ASan to track down Janus bugs

---

ansible/roles/squawk/templates/squawkers.sh.j2

This corresponds to the changes in https://github.com/mozilla/hubs/pull/476.

Update squawkers script

---

ansible/roles/janus/templates/janus-gateway.toml.j2

Nobody wants it to be 16 anymore.

Increase max room size to 64

---

ansible/roles/ret/templates/reticulum.toml.j2

Added slack client bot secrets + slack controller token

updated with slack references

---

terraform/modules/slackbot/mr-ops-command-slackbot/main.js

Updates and simplifies the mr slack command script.

Ops command slackbot update

---

cloudformation/stack.yaml

Learnings recorded here : https://gist.github.com/netpro2k/4fc11d880a3b74bc630422e89108c19e

Rename stack variables

---

terraform/modules/slackbot/mr-ops-command-slackbot/main.js

Adds slack commands for kicking off the QA build promotion job

Slack commands for promoting QA builds

---

cloudformation/stack.yaml

- Replaced botocore.requests with urllib3

Remove deprecated botocore.requests library 

---

cloudformation/stack.yaml

https://github.com/mozilla/hubs-ops/pull/107
https://github.com/mozilla/hubs-ops/pull/99
https://github.com/mozilla/hubs-ops/pull/97
QA tests -- see qa test plans in each respective PR.

Combined template changes for QA test: 107, 99, 97

---

cloudformation/stack.yaml

Investigating missing assets for enterprise multi-server HC stacks.

Added if statement for asset cloudfront alb

---

terraform/modules/ret/main.tf

For https://github.com/mozilla/reticulum/pull/544

Allow UDP DNS egress

---

workers/cors-proxy-internal.js

This PR runs prettier on the proxy worker code, and improves the clarity of the code. It's split into two commits, so you can focus on the second commit https://github.com/mozilla/hubs-ops/pull/164/commits/c7145a3e20e33eb04b971bff48ff5d070eaa40b6

Prettier proxy

---

.github/workflows/HcPkgPreReleaseGitops.yaml

Capitalized the Y in the tag variable
Added capitalized all the first words in the echo outputs

Fixed capitalization for y in tag varible and echo's 

---

.github/workflows/turkeyGitops.yml

This will allow deploying set docker image to a smoke instance namespace given in the drop down.

Add new job to Turkey ops workflow to deploy to smoke instance. 

---

cloudformation/stack.yaml

Updates to cloud formation will be released in version 1.1.
Bug Fix: Taking Stack offline breaks stack 
Sets wait for the response signal to false 
Security fix: 
updates photomnemonic to version 0.3.3.

updates to cloudformation that will be published in marketplace version 1.1.6

---

cloudformation/stack.yaml

Set the version number in the Description to 1.1.6. 
Set Public S3  buckets to reflect new security standards set by AWS.

Set template to reflect version that will be published in version 1.1.6.

---

.github/workflows/turkeyGitops.yml

Use the Hubs Foundation's docker hub repository and comment out anything that the Hubs Foundation doesn't have infrastructure for.

Hubs Foundation docker registry update
